#!/usr/bin/env bash
# Check if the user provided an argument then excute the command pingto look at the ICMP protocol, which is used to check if a host is on the network. else, print the usage of the script and exit with status 1.
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 0
fi
IP_ADDRESS=$1
ping -c 5 "$IP_ADDRESS"
